<?php

//Define the SMTP settings for the AWS Simple Email Service
define("EMAIL_TO_ADDRESS", "<EMAIL_TO_ADDRESS>");
define("EMAIL_FROM_ADDRESS", "<EMAIL_FROM_ADDRESS>");
define("EMAIL_FROM_NAME", "<EMAIL_FROM_NAME>");
define("EMAIL_SMTP_USERNAMAE", "<EMAIL_SMTP_USERNAMAE>");
define("EMAIL_SMTP_PASSWORD", "<EMAIL_SMTP_PASSWORD>");
define("EMAIL_HOST", "<EMAIL_HOST>");
define("EMAIL_PORT", "<EMAIL_PORT>");
define("EMAIL_BODY_TEMPLATE", '<EMAIL_BODY_TEMPLATE>');
?>